# Generated by Django 4.2.11 on 2024-04-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_alter_keyword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
