# Generated by Django 4.2.11 on 2024-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_alter_keyword_created_at_alter_trend_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
