# Generated by Django 4.2.2 on 2024-04-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='debut_data',
            new_name='debut_date',
        ),
    ]
