# Generated by Django 4.2.11 on 2024-04-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(related_name='product', to='malls.product'),
        ),
    ]
