# Generated by Django 4.2.2 on 2024-03-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='pub_date',
        ),
    ]
