# Generated by Django 4.2.11 on 2024-04-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_product',
            field=models.ManyToManyField(to='malls.product'),
        ),
    ]
