# Generated by Django 4.2.11 on 2024-04-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0002_customer_customer_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
