# Generated by Django 4.2.11 on 2024-04-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='total_fee',
        ),
    ]
