# Generated by Django 4.2.11 on 2024-04-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_attendance_total_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
